apiVersion: v1
kind: ConfigMap
metadata:
  name: postgre-product-schema
  namespace: argo-kube-test
data:
  schema.sql: |
    -- Script SQL pour cr√©er les tables et les relations de la base Product
    CREATE TABLE IF NOT EXISTS products (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      price DECIMAL NOT NULL
    );
    -- Ajoutez d'autres tables et relations ici
